### ISSUE TITLE
Nextcloud Docker image should use DNS server of UCS host

### ISSUE THREAD

**Issue by ngulden** [nextcloud/univention-app#103]
The Nextcloud Docker image uses Google's DNS 8.8.8.8 in its `/etc/resolv.conf`. It therefore can only resolve public domains. Internal hostnames from the intranet served by the UCS environment cannot be resolved by the Docker container.

As a side note, see https://forge.univention.org/bugzilla/show_bug.cgi?id=44845

**Comment by blizzz** [comment]
@ngulden with a fresh installation, the DNS in the Nextcloud container points at the local machine (via internal IP), not 8.8.8.8. Some for an already existing installation. DNS settings are the default from the Ubuntu docker image.

Could it be a thing from the appliance?

Otherwise I am unsure what to read out from the UCR to set as name server. With appliances in mind, I cannot use the local hosts IP at install time, right.

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
