### ISSUE TITLE
Client 2.2.4 Unable To Connect To Nextcloud 11

### ISSUE THREAD

**Issue by sixshooterz** [nextcloud/univention-app#2]
This client was able to connect to Nextcloud 10 but fails when connecting to the new version.  I've not tested platforms other than Univention so I'm not sure if this is specific to this docker instance.  Please advise.

EDIT:  It seems the client has it hard-coded that the trailing URL should be owncloud instead of nextcloud or looking for status.php in the root.  I am able to connect to https://mail.sixshooterz.com/nextcloud/status.php without issue.
![nextcloud](https://cloud.githubusercontent.com/assets/12206020/23289003/e25353d4-fa14-11e6-9bee-c40a3067594c.png)

**Comment by blizzz** [comment]
You also need to specify the path, if Nc is not installed in the domain root. Which is the case on UCS, obviosuly, so you need to provide the ``nextcloud`` folder.

About the client: the current state is that we use the same source as upstream and only change the theming capabilities. Probably that's why it looks up the owncloud subfolder.

**Comment by blizzz** [comment]
Yes, it's not part of the theming capabilities, yet. Anyhow it is a client issue, thus closing.
